title = "Carlo Buccisano"
author = "Carlo Buccisano"
#description = "Math PhD"

profilePicture = "images/avatar.jpg"
displayMode = "dark"
favicon = "favicons/"

contentratio=0.8

singleDateFormat = "Mon, Jan 2, 2006"
indexDateFormat = "Mon, Jan 2, 2006"
listDateFormat = "Jan 2"

#mainSections = []

#Google Fonts
#googleFonts = ["Ubuntu", "Roboto", "Open Sans"]

#disableThemeSwitcher = true # Theme switcher is enabled by default

## Math settings

math = true
katex = true    # The alternative is mathjax, but Hugo seems to prefer KaTeX

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:carlo.buccisano@universite-paris-saclay.fr"

[[socialIcons]]
icon = "fab fa-github"
title = "github"
url = "https://www.github.com/carlobuccisano"

[[socialIcons]]
icon = "fa-brands fa-orcid"
title = "ORCiD"
url = "https://orcid.org/0009-0001-9023-8754"
